# Generated by Django 4.2.7 on 2023-11-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
                ('message', models.TextField(default=None, null=True)),
                ('traceId', models.CharField(max_length=255)),
                ('spanId', models.CharField(max_length=255)),
                ('commit', models.CharField(max_length=255)),
                ('parentResourceId', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('resourceId', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
